- name: Make sure specified user is in the sudoers file with NOPASSWD
  community.general.sudoers:
    name: "{{ user }}_sudo_config"
    user: "{{ user }}"
    nopassword: true
    commands: ALL
    state: present

- name: Create home directory dotfiles for user
  ansible.builtin.template:
    src: "../files/{{ item }}.j2"
    dest: "/home/{{ user }}/.{{ item }}"
    mode: u=rw,g=r,o=
  loop:
    - gitconfig
    - bash_profile
    - bashrc
