---
- name: Ensure cockpit service is enabled and running
  ansible.builtin.systemd_service:
    name: "{{ service }}"
    enabled: true
    state: started
  loop: "{{ services_enabled_started }}"
  loop_control:
    loop_var: service
